server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AddRequestHeader=X-Internal-Call, true

        - id: user-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AddRequestHeader=X-Internal-Call, true

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AddRequestHeader=X-Internal-Call, true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true