server:
  port: 8082

spring:
  application:
    name: product-service

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

  datasource:
    url: jdbc:postgresql://localhost:5433/productdb
    username: aziz
    password: password_123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:3000/eureka


